"""empty message

Revision ID: 141c85333cb
Revises: 37c84eaa437
Create Date: 2014-08-02 15:30:42.380999

"""

# revision identifiers, used by Alembic.
revision = '141c85333cb'
down_revision = '37c84eaa437'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('presentations', 'talk_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('presentations', 'talk_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
