"""Add slugs to events.

Revision ID: 177a65486a0
Revises: 32dc1be3b22
Create Date: 2015-04-27 04:40:15.594924

"""

# revision identifiers, used by Alembic.
revision = '177a65486a0'
down_revision = '32dc1be3b22'

from alembic import op
from slugify import slugify
import sqlalchemy as sa
from sqlalchemy import Integer, String
from sqlalchemy.sql import table, column

events_table = table(
    'events',
    column('id', Integer),
    column('name', String),
    column('slug', String),
)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('slug', sa.String(length=75), nullable=True))
    op.create_unique_constraint('events_slug_key', 'events', ['slug'])
    ### end Alembic commands ###

    conn = op.get_bind()
    events = conn.execute(events_table.select())
    for event in events:
        if not event.slug:
            op.execute(
                events_table.update().where(
                    events_table.c.id == event.id
                ).values(
                    slug=slugify(event.name)
                )
            )

    op.alter_column('events', sa.Column('slug', sa.String(length=75), nullable=False))


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_slug_key', 'events', type_='unique')
    op.drop_column('events', 'slug')
    ### end Alembic commands ###
