"""Add volunteers.

Revision ID: 254d12951cf
Revises: 62214735b8
Create Date: 2015-06-22 16:36:21.192902

"""

# revision identifiers, used by Alembic.
revision = '254d12951cf'
down_revision = '62214735b8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('volunteers_event_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('volunteers_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('volunteers_pkey'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volunteers')
    ### end Alembic commands ###
