"""Move talk duration to a separate table.

Revision ID: 32dc1be3b22
Revises: 55a2c1bad7
Create Date: 2015-04-24 05:17:47.640955

"""

# revision identifiers, used by Alembic.
revision = '32dc1be3b22'
down_revision = '55a2c1bad7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Boolean, Integer, String
from sqlalchemy.sql import table, column

durations_table = table(
    'durations',
    column('name', String),
    column('duration', Integer),
    column('inactive', Boolean),
)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('durations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('inactive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('talks', sa.Column('duration_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'talks', 'durations', ['duration_id'], ['id'])
    ### end Alembic commands ###

    op.bulk_insert(durations_table, [
        {'name': '30 minutes', 'duration': 30, 'inactive': False},
        {'name': '45 minutes', 'duration': 45, 'inactive': False},
        {'name': '60 minutes', 'duration': 60, 'inactive': False},
        {'name': '1/2 day', 'duration': 180, 'inactive': False},
        {'name': 'full day', 'duration': 360, 'inactive': False},
    ])

    op.execute(
        'UPDATE talks AS t SET duration_id = d.id FROM durations AS d WHERE t.duration::text = d.name')

    op.alter_column('talks', 'duration_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('talks', 'duration')
    context = op.get_context()
    if context.bind.dialect.name == 'postgresql':
        sql = "DROP TYPE duration"
        op.execute(sql)


def downgrade():
    context = op.get_context()
    if context.bind.dialect.name == 'postgresql':
        sql = "CREATE TYPE duration AS ENUM ('{}', '{}', '{}', '{}', '{}')"
        op.execute(sql.format('30 minutes', '45 minutes', '60 minutes', '1/2 day', 'full day'))

    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('talks', sa.Column('duration', sa.Enum('30 minutes', '45 minutes', '60 minutes', '1/2 day', 'full day', name='duration')))
    op.execute(
        'UPDATE talks AS t SET duration = d.name::duration FROM durations AS d WHERE t.duration_id = d.id')
    op.alter_column('talks', sa.Column('duration', sa.Enum('30 minutes', '45 minutes', '60 minutes', '1/2 day', 'full day', name='duration')))
    op.drop_column('talks', 'duration_id')
    op.drop_table('durations')
    ### end Alembic commands ###
