"""Add speaker bio.

Revision ID: 3a8f2b6a733
Revises: 4275b4cb207
Create Date: 2014-05-16 23:24:30.585238

"""

# revision identifiers, used by Alembic.
revision = '3a8f2b6a733'
down_revision = '4275b4cb207'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    ### end Alembic commands ###
