"""Add a start date for an event's talk list.

Revision ID: 4175dff441
Revises: 53119f86c67
Create Date: 2014-07-18 00:18:23.595894

"""

# revision identifiers, used by Alembic.
revision = '4175dff441'
down_revision = '53119f86c67'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('talk_list_begins', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'talk_list_begins')
    ### end Alembic commands ###
