"""empty message

Revision ID: 4275b4cb207
Revises: b8dc37a1f5
Create Date: 2014-04-26 00:10:11.985242

"""

# revision identifiers, used by Alembic.
revision = '4275b4cb207'
down_revision = 'b8dc37a1f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('talks', 'recording_release',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('talks', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('talks', 'recording_release',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('talks', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
