"""Add a video URL to talks.

Revision ID: 55a2c1bad7
Revises: 141c85333cb
Create Date: 2014-08-17 11:45:59.088303

"""

# revision identifiers, used by Alembic.
revision = '55a2c1bad7'
down_revision = '141c85333cb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('talks', sa.Column('video_url', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('talks', 'video_url')
    ### end Alembic commands ###
