"""Add Twitter handle to users.

Revision ID: 564d901de0c
Revises: 4a435efab65
Create Date: 2015-06-13 15:13:30.330527

"""

# revision identifiers, used by Alembic.
revision = '564d901de0c'
down_revision = '4a435efab65'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('twitter_handle', sa.String(length=15), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'twitter_handle')
    ### end Alembic commands ###
