"""Switch navbar_section to navbar_path

Revision ID: 5d619660cfa7
Revises: 9d4ba8cee
Create Date: 2016-04-12 01:25:26.100358

"""

# revision identifiers, used by Alembic.
revision = '5d619660cfa7'
down_revision = '9d4ba8cee'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'about_pages',
        sa.Column(
            'navbar_path',
            postgresql.ARRAY(sa.String()),
            nullable=False,
            server_default='{}',
        ),
    )
    op.create_unique_constraint('ix_about_pages_navbar_path_slug_event_id', 'about_pages', ['navbar_path', 'slug', 'event_id'])
    op.execute(
        'UPDATE about_pages '
        'SET navbar_path=ARRAY[navbar_section, title]'
    )
    op.drop_constraint('ix_about_pages_navbar_section_slug_event_id', 'about_pages', type_='unique')
    op.drop_column('about_pages', 'navbar_section')
    ### end Alembic commands ###


def downgrade():
    raise NotImplemented('This migration cannot be cleanly downgraded.')
