"""empty message

Revision ID: 9d0181579c
Revises: 22ec375d28e
Create Date: 2014-01-19 01:02:12.456219

"""

# revision identifiers, used by Alembic.
revision = '9d0181579c'
down_revision = '22ec375d28e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    ### end Alembic commands ###
