"""empty message

Revision ID: b8dc37a1f5
Revises: 9d0181579c
Create Date: 2014-04-16 22:54:41.449111

"""

# revision identifiers, used by Alembic.
revision = 'b8dc37a1f5'
down_revision = '9d0181579c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    context = op.get_context()
    if context.bind.dialect.name == 'postgresql':
        sql = "CREATE TYPE duration AS ENUM ('{}', '{}', '{}', '{}', '{}')"
        op.execute(sql.format('30 minutes', '45 minutes', '60 minutes', '1/2 day', 'full day'))
        sql = "CREATE TYPE type AS ENUM ('{}', '{}')"
        op.execute(sql.format('talk', 'tutorial'))

    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('talks', sa.Column('duration', sa.Enum('30 minutes', '45 minutes', '60 minutes', '1/2 day', 'full day', name='duration'), nullable=False))
    op.add_column('talks', sa.Column('type', sa.Enum('talk', 'tutorial', name='type'), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('talks', 'type')
    op.drop_column('talks', 'duration')
    ### end Alembic commands ###

    context = op.get_context()
    if context.bind.dialect.name == 'postgresql':
        op.execute('DROP TYPE duration')
        op.execute('DROP TYPE type')
