"""Add announcements.

Revision ID: f34e9df528
Revises: 3a8f2b6a733
Create Date: 2014-05-24 23:24:36.623596

"""

# revision identifiers, used by Alembic.
revision = 'f34e9df528'
down_revision = '3a8f2b6a733'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('published', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('announcements')
    ### end Alembic commands ###
